name: CI e Deploy para GitHub Pages

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Mensagem:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer o git clone
        uses: actions/checkout@v4

      - name: Executando primeiro comando
        run: |
          ls -l
          echo "Fim do Processo"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
